/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myStore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author skh
 */
public class ReceiveOrder extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    /**
     * Creates new form PlaceOrder
     */
    public ReceiveOrder() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf3 = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receive Order", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enter orderno. : ");

        tf1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Date : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Dealer name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Order Amount : ");

        tf4.setEditable(false);
        tf4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tf2.setEditable(false);
        tf2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no.", "Product name", "Cost price of 1 unit", "Quantity ordered ", "Quantity received", "Status "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.setRowMargin(2);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Save Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("  Clear  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("  Close  ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tf3.setEditable(false);
        tf3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addGap(354, 354, 354)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(221, 221, 221)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tf1.getText().equals(""))
            return;
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String sql;
        try
        {
            try
            {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store","root","admin");
                st = con.createStatement();

                for(int r = 0 ; r < dtm.getRowCount() ; r++)
                {
                    
                    if((!dtm.getValueAt(r,5).equals("N")) && (!dtm.getValueAt(r,5).equals("Y")))
                    {
                        JOptionPane.showMessageDialog(this,"Wrong Status entered in serial number : " + 
                                (r+1) + ".\nPlease enter the status in the form of a single character"
                                + " : 'Y' or 'N'.");
                        
                        if(!rs.isClosed())
                        rs.close();
                        if(!st.isClosed())
                        st.close();
                        if(!con.isClosed())
                        con.close();
                        return;
                    }
                    
                    if(("" + dtm.getValueAt(r,4)).trim().equals("") && dtm.getValueAt(r,5).equals("Y"))
                    {        
                        JOptionPane.showMessageDialog(this,"Please enter the quantity received in "
                                    + "serial number = " + (r+1) + ".");
                        if(!rs.isClosed())
                        rs.close();
                        if(!st.isClosed())
                        st.close();
                        if(!con.isClosed())
                        con.close();
                        return;
                    }
                }
                //JOptionPane.showMessageDialog(this,"loop over.");
                        
                
                
                for(int r = 0 ; r < dtm.getRowCount() ; r++)
                {
                    if(dtm.getValueAt(r,5).equals("N"))
                        continue;
                    
                    if(dtm.getValueAt(r,5).equals("Y"))
                    {
                        String itemname = (dtm.getValueAt(r, 1)+ "");
                        sql = "select * from packeditems where itemname = '" + itemname + "';";
                        rs = st.executeQuery(sql);
                        rs.next();
                        int pino = rs.getInt("pino");
                        rs.close();
                        
                        sql = "update orderdetails set status = 'Y' where orderno = " + 
                                tf1.getText() + " and pino = " + 
                                pino + ";";
                        st.executeUpdate(sql);
                        
                        sql = "select * from packeditemdetails where pino = " + pino + 
                                " and cp1unit = " + dtm.getValueAt(r, 2) + ";";
                        rs = st.executeQuery(sql);
                        
                        if(rs.next())
                        {
                            int totalQty = rs.getInt("qtyathand");
                            totalQty += Integer.parseInt("" + dtm.getValueAt(r, 4));
                            sql = "update packeditemdetails set qtyathand = " + totalQty +
                                    " where pino = " + pino + " and cp1unit = " + dtm.getValueAt(r, 2)
                                    + ";";
                            st.executeUpdate(sql);
                            rs.close();
                            
                            sql = "select * from orderdetails where orderno = " + tf1.getText() +
                                    " and pino = " + pino + ";";
                            rs = st.executeQuery(sql);
                            rs.next();
                            int qtyreceived = rs.getInt("qtyreceived");
                            rs.close();
                            qtyreceived += Integer.parseInt("" + dtm.getValueAt(r,4));
                            sql = "update orderdetails set qtyreceived = " + qtyreceived + 
                                    " where orderno = " + tf1.getText() +
                                    " and pino = " + pino + ";";
                            st.executeUpdate(sql);
                        }
                        else
                        {
                            rs.close();
                            int totalQty = Integer.parseInt("" + dtm.getValueAt(r, 4));
                            sql = "insert into packeditemdetails (pino,cp1unit,qtyathand)"
                                    + " values ('" + pino + "','" + dtm.getValueAt(r, 2) + "','" + 
                                    totalQty  + "');" ;
                            st.executeUpdate(sql);
                            
                            sql = "select * from orderdetails where orderno = " + tf1.getText() +
                                    " and pino = " + pino + ";";
                            rs = st.executeQuery(sql);
                            rs.next();
                            int qtyreceived = rs.getInt("qtyreceived");
                            rs.close();
                            qtyreceived += Integer.parseInt("" + dtm.getValueAt(r,4));
                            sql = "update orderdetails set qtyreceived = " + qtyreceived + 
                                    " where orderno = " + tf1.getText() +
                                    " and pino = " + pino + ";";
                            st.executeUpdate(sql);
                            
                        }
                        
                        
                    }
                    
                }
                JOptionPane.showMessageDialog(this,"Record saved.");
                jButton2.doClick();
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
            finally
            {
                if(!rs.isClosed())
                rs.close();
                if(!st.isClosed())
                st.close();
                if(!con.isClosed())
                con.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Badi Gadbad.");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        
        int total = dtm.getRowCount();
        for(int r = 0 ; r < total ; r++)
        {
            dtm.removeRow(0);
        }
        tf1.setEnabled(true);
        tf1.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
            jTable1.requestFocus();
        
        if(ch >= '0' && ch <= '9')
        {
            if(ch == '0')
                if(Integer.parseInt(tf1.getText()) == 0)
                    evt.consume();
        }
        else
            evt.consume();
    }//GEN-LAST:event_tf1KeyTyped

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String sql;
        try
        {
            try
            {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/store","root","admin");
                st = con.createStatement();

                sql = "select * from orders where orderno = '" + 
                        tf1.getText() + "'";
                rs = st.executeQuery(sql);
                if(rs.next())
                {
                    tf1.setEnabled(false);
                    tf2.setText("" + rs.getString(2));
                    tf3.setText("" + rs.getString(3));
                    tf4.setText("" + rs.getString(4));
                    rs.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Wrong order number entered.");
                    return;
                }
                
                sql = "select * from dealers where did = '" + tf2.getText() + "';";
                rs = st.executeQuery(sql);
                rs.next();
                tf2.setText("" + rs.getString("dname"));
                rs.close();
                
                sql = "select * from orderdetails where orderno = " + tf1.getText() + ";";
                rs = st.executeQuery(sql);
                int i = 0;
                while(rs.next())
                {
                    i++;
                    Object row[] = {i,
                                    rs.getString("pino"),
                                    rs.getString("cp1unit"),
                                    rs.getString("qtyordered"),
                                    rs.getString("qtyreceived"),
                                    rs.getString("status")
                                    };
                    dtm.addRow(row);
                }
                rs.close();
                
                for(int r = 0; r < dtm.getRowCount() ; r++)
                {
                    int pino = Integer.parseInt("" + dtm.getValueAt(r, 1));
                    sql = "select * from packeditems where pino = '" + pino + "';";
                    rs = st.executeQuery(sql);
                    rs.next();
                    dtm.setValueAt(rs.getString("itemname"), r, 1);
                    rs.close();
                                         
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
            finally
            {
                if(!rs.isClosed())
                rs.close();
                if(!st.isClosed())
                st.close();
                if(!con.isClosed())
                con.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Badi Gadbad.");
        }
        
        
    }//GEN-LAST:event_tf1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
